name: Build and Scan .NET Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Install .NET Tools
        run: |
            dotnet tool install --global dotnet-sonarscanner --version 9.0.2 && \
            dotnet tool install --global coverlet.console --version 6.0.4 

      - name: Set Working Directory
        run: cd ./sonarqube-github-actions/unit-testing-using-dotnet-test/PrimeService.Tests/
      
      - name: Restore Dependencies
        run: dotnet restore PrimeService.Tests.csproj
      
      - name: Build Test Project
        run: dotnet build PrimeService.Tests.csproj --configuration Debug

      - name: Run Tests With Coverage
        run: |
          dotnet test --configuration Debug --output ../../output-tests \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            /p:CoverletOutput='coverage.opencover.xml'   
    
      - name: Run .NET Scanner
        run: dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"